[runtime]
worker_threads = 4
thread_stack_size_mb = 3
max_blocking_threads = 4

[process]
enable_backtrace = true
debug_logging = false

[shutdown]
graceful_timeout_secs = 30

[aws]
connection_pool_size = 10
retry_attempts = 3
timeout_secs = 30

# Logging Configuration
[logging]
# Enable/disable logging (default: true)
enabled = false
# Log level: "error", "warn", "info", "debug", or "trace" (default: "info")
level = "info"
# Maximum size of each log file in bytes (default: 10MB)
max_size = 10485760  # 10 * 1024 * 1024 bytes
# Maximum number of backup log files to keep (default: 7)
max_files = 7
# Directory where log files will be stored (default: "logs")
log_dir = "logs"
